# Generated by Django 5.1.1 on 2024-10-04 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0002_task_manager_db_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_manager_db',
            new_name='TaskManagerDb',
        ),
    ]
