# Generated by Django 5.1.1 on 2024-10-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0003_rename_task_manager_db_taskmanagerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_russian', models.CharField(max_length=30)),
                ('text_english', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CardsCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskManagerDb',
        ),
    ]
